### PR TITLE
[SSR] Fix "navigator is not defined"

### PR DESCRIPTION
**Pull request by LeoLeBras**
Related https://github.com/nicolaslopezj/simple-react-form/issues/66

### CODE REVIEW

**Comment by LeoLeBras** [comment]
@nicolaslopezj ?

**Comment by fermuch** [comment]
This PR works perfectly for me. Anything to add, @nicolaslopezj ?

**Comment by nicolaslopezj** [comment]
Sorry for the delay

**Comment by joadr** [comment]
This PR Breaks non react native installs!

**Comment by fermuch** [comment]
@joadr it's working for me on the browser. What error do you have? does it come from `isRN`?

**Pull request merged**
