### PR TITLE
Tests for issue #29 - Create tests

### PR DESCRIPTION
**Pull request by fermuch**
This branch is to document my progress while adding tests to the project.
The reason for making a PR instead of discussing in the issue itself is so we can add comments to each test _before_ merging to master.

If you find something else you'd like to test, a problem with a test, or want to ask something in general about this branch, just comment here, and if needed add a comment to the code itself. I'm not used to the project codebase, so I may forget to test some things.

### TESTS ADDED

- [x] Clean nulls helper
- [x] Doc to modifier helper (Can't test, depends on meteor package)
- [x]  Replace index keys helper
- [x]  Report nulls helper
- [x]  onValueChange function on form
- [x] Form is rendered correctly
- [x]  Automatic input generation
- [x] Array field is working correctly (this has a history of troubles, test would be great here)
- [x] Object field is working correctly

### TESTS TO ADD

### CODE REVIEW

**Comment by fermuch** [comment]
@nicolaslopezj I'm not sure what should be tested by "automatic input generation". To render the `type` in the `Field`? or something else?

**Comment by nicolaslopezj** [comment]
@fermuch this function https://github.com/nicolaslopezj/simple-react-form/blob/master/src/form.js#L420

**Comment by nicolaslopezj** [comment]
This is awesome

**Comment by fermuch** [comment]
Thanks : D

Only object & array fields left, but not so trivial to test.
Maybe tomorrow I'll finish those, and we can merge to master!

**Comment by fermuch** [comment]
I think everything is ready! Woohoo!

**Pull request merged**
