### PR TITLE
Make Form working with SimpleSchema 2.0 while

### PR DESCRIPTION
**Pull request by prinzdezibel**
keeping backwards compatibility with older versions of SimpleSchema.

### CODE REVIEW

**Comment by prinzdezibel** [comment]
Hi @nicolaslopezj! Did you already have time to check this PR? Cheers, Michael

**Comment by nicolaslopezj** [comment]
Sorry for the delay!

**Comment by nicolaslopezj** [comment]
Published in v1.9.1

**Comment by JulianKingman** [comment]
Does this fix the MongoObject global mentioned in #58? I'm still getting that error.

**Pull request merged**
